-- Run this once in the Supabase SQL Editor for project pdwmjdejduqjmafspnrr.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  provider text not null,
  address text not null,
  chain text not null default 'multi-chain',
  created_at timestamptz not null default now(),
  unique (user_id, address)
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  wallet_id bigint references public.wallets(id) on delete set null,
  type text not null,
  detail text not null,
  status text not null default 'pending',
  tx_hash text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  transaction_id bigint references public.transactions(id) on delete set null,
  type text not null,
  detail text not null,
  status text not null,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.wallets enable row level security;
alter table public.transactions enable row level security;
alter table public.activity enable row level security;

-- Prototype policies: replace these with auth.uid()-based policies before production.
create policy "prototype users access" on public.users for all to anon, authenticated using (true) with check (true);
create policy "prototype wallets access" on public.wallets for all to anon, authenticated using (true) with check (true);
create policy "prototype transactions access" on public.transactions for all to anon, authenticated using (true) with check (true);
create policy "prototype activity access" on public.activity for all to anon, authenticated using (true) with check (true);

create index if not exists wallets_user_id_idx on public.wallets(user_id);
create index if not exists transactions_user_id_idx on public.transactions(user_id);
create index if not exists activity_user_id_idx on public.activity(user_id);
